/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as MiReservaRouteImport } from './routes/mi-reserva'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiculoIdRouteImport } from './routes/vehiculo.$id'

const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReservaRoute = MiReservaRouteImport.update({
  id: '/mi-reserva',
  path: '/mi-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculoIdRoute = VehiculoIdRouteImport.update({
  id: '/vehiculo/$id',
  path: '/vehiculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mi-cuenta'
    | '/mi-reserva'
    | '/reservar'
    | '/vehiculo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mi-cuenta'
    | '/mi-reserva'
    | '/reservar'
    | '/vehiculo/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mi-cuenta'
    | '/mi-reserva'
    | '/reservar'
    | '/vehiculo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MiCuentaRoute: typeof MiCuentaRoute
  MiReservaRoute: typeof MiReservaRoute
  ReservarRoute: typeof ReservarRoute
  VehiculoIdRoute: typeof VehiculoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reserva': {
      id: '/mi-reserva'
      path: '/mi-reserva'
      fullPath: '/mi-reserva'
      preLoaderRoute: typeof MiReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculo/$id': {
      id: '/vehiculo/$id'
      path: '/vehiculo/$id'
      fullPath: '/vehiculo/$id'
      preLoaderRoute: typeof VehiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MiCuentaRoute: MiCuentaRoute,
  MiReservaRoute: MiReservaRoute,
  ReservarRoute: ReservarRoute,
  VehiculoIdRoute: VehiculoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
